### PR TITLE
PXY-204 Architecture diagram

### PR DESCRIPTION
**Pull request by vuduchailinh**

### CODE REVIEW

**Comment by ehumber** [comment]
Nice diagram, thank you!

Only bit of feedback is that Zookeeper is the biggest part of the whole diagram, but it's probably the least relevant. Could you make it the same size, or smaller than SR and Platform please?

@AurelieMarcuzzo raised the requirement for the diagram, so I think we should ask her if it covers what she was asking for.

**Comment by AurelieMarcuzzo** [comment]
Hi there 👋 Thank you for that !

I like it, it's more visual so we can understand what is going on. My only remark is a personal request: Do you think it's possible, especially for Multi-Tenancy, to show the different tenant that we have (London, Paris)? I think this is the feature that needs to be drawn so we see the inside of the magic.

**Comment by vuduchailinh** [comment]
Thanks @ehumber, @AurelieMarcuzzo, updated -> [257a035](https://github.com/conduktor/conduktor-proxy-demos/pull/22/commits/257a035701803cd2715c9cead6737f4c1b1159dc). 
Multi tenants updated here -> https://github.com/conduktor/conduktor-proxy-demos/tree/linh/architecture-diagram/multi-tenant, hope you like it

**Comment by ehumber** [comment]
Tiny comment - add a dotted line from proxy to kafka:9093 as well, as proxy talks to all brokers and at the moment it looks like it only talks to one of them.

**Review by ehumber — APPROVED** [review]

**Comment by AurelieMarcuzzo** [comment]
That's perfect, thank you a lot !

**Pull request merged**
